site_name: Xcmd - 常用命令速查
site_description: 常用命令速查 - Redis常用命令、Kafka常用命令、MySQL常用命令
site_url: https://xcmd.run
use_directory_urls: true

theme:
  name: material
  palette:
    primary: deep purple
  language: zh
  icon:
    logo: material/access-point


plugins:
  - search:
      lang:
        - en

nav:
  - 首页: 'index.md'
  - Redis: 'redis.md'
  - Zookeeper: 'zookeeper.md'
  - Kafka: 'kafka.md'
  - MySQL: 'mysql.md'
